[stack]
framewarp = [0xC, 0x4C]
pattern = [0xC, 0x8, 0x0, 0x44]
pattern_timer = [0xC, 0x8, 0x0, 0x64]
boss_hp = [0xC, 0x8, 0x0, 0x58]
boss_iframe = [0xC, 0x8, 0x0, 0x60]
score = [0xC, 0x0, 0x0, 0x58]
life = [0xC, 0x0, 0x0, 0x48]
bomb = [0xC, 0x0, 0x0, 0x60]
thrill = [0xC, 0x0, 0x0, 0x5C]
flash_gauge = [0xC, 0x0, 0x0, 0x6C]
bomb_timer = [0xC, 0x0, 0x0, 0x64]

[stack.le02]
total_point = [0xC, 0x0, 0x0, 0x80]
point = [0xC, 0x0, 0x0, 0x84]
power = [0xC, 0x0, 0x0, 0x7C]
flower_gauge = [0xC, 0x0, 0x0, 0x8C]
iframe = [0xC, 0x0, 0x248]
shoot_dur = [0xC, 0x0, 0x0, 0x90]

# le03 v1.21a. As for versions below, there's a bug for total_point. Needs check.
[stack.le03]
total_point = [0xC, 0x0, 0x0, 0x84]
point = [0xC, 0x0, 0x0, 0x88]
power1 = [0xC, 0x0, 0x0, 0x7C]
power2 = [0xC, 0x0, 0x0, 0x80]
spirit = [0xC, 0x0, 0x0, 0x94]
iframe = [0xC, 0x0, 0x374]
shoot_dur = [0xC, 0x0, 0x0, 0x98]

[le01]
keys = 0xAE7A34
stage = 0xAE7780
diff = 0xAE7780
shot = 0xAE7784

[le02]
stage = 0xADDFF0
diff = 0xADDFE8

[le03]
stage = 0xB0A548
diff = 0xB0A53C

[le02.tasouken]
phase = 0x5E0888
phase_length = 0x6B839
starting_phase = 0x6B7C0
starting_timer = 0x2772A

[le03.PMiBR]
jump_code = 0x71899
screenclear1 = 0x71894
timer1 = 0x2B1B0
timer2 = 0x28F28
