trick_nostalgie = "https://mugentrick.tubakurame.com"

lenen_wiki = "https://lenen.wiki.gg"
lenen_thbwiki = "https://thwiki.cc/-/21qv"
lenen_wiki_ja = "https://lenen.wiki.gg/ja"
lenen_wiki_ru = "https://ruslenenwiki.shoutwiki.com"
lenen_wiki_ja_old = "https://w.atwiki.jp/len_en"

unreal_world_of_mugenri = "https://discord.com/invite/6keJAnX"

lenen_game_archive_collection_wiki = "https://lenen.wiki.gg/wiki/Len'en_Game_Archive_Collection"
lenen_game_archive_collection_docs = "https://docs.google.com/spreadsheets/d/e/2PACX-1vT9uja84HDrNHTaPwILiDZHIYxsUjFARZUqgdwnmWQzcT-Lhyr5t7SrEA4ZrOtvaLSlky7iOlSepi1A/pubhtml"

github_repo = "https://github.com/BAN-43-32532/leprac"
github_release = "https://github.com/BAN-43-32532/leprac/releases/latest"
github_release_api = "https://api.github.com/repos/BAN-43-32532/leprac/releases/latest"

[download]
Le01_official = "https://www.freem.ne.jp/win/game/15994"
Le02_official = "https://www.freem.ne.jp/win/game/15995"
Le03_official = "https://www.freem.ne.jp/win/game/15996"
Le04_official = "https://www.freem.ne.jp/win/game/13429"
Uso_official = "https://www.freem.ne.jp/win/game/15082"

resize_enable = "http://www.digitallis.co.uk/pc/downloads/ResizeEnable.zip"